"""add_duration_seconds_to_record

Revision ID: 118966d219d7
Revises: aafaf157ff08
Create Date: 2025-07-16 11:29:32.711895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "118966d219d7"
down_revision: Union[str, None] = "aafaf157ff08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add duration_seconds column to record table
    op.add_column("record", sa.Column("duration_seconds", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove duration_seconds column from record table
    op.drop_column("record", "duration_seconds")
    # ### end Alembic commands ###
