"""add file_hash to record table

Revision ID: 2ed7a8955b7a
Revises: ed5b5ea7def8
Create Date: 2025-08-14 15:54:26.091988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2ed7a8955b7a"
down_revision: Union[str, None] = "ed5b5ea7def8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "record", sa.Column("file_hash", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("record", "file_hash")
    # ### end Alembic commands ###
