"""update record schema to match current model

Revision ID: 58cec5cbaa6d
Revises: 8133bfd89d7c
Create Date: 2025-06-03 02:20:12.346288

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "58cec5cbaa6d"
down_revision: Union[str, None] = "8133bfd89d7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("record", sa.Column("title", sa.String(length=200), nullable=False))
    op.add_column(
        "record", sa.Column("description", sa.String(length=1000), nullable=True)
    )
    op.add_column(
        "record",
        sa.Column(
            "media_type",
            sa.Enum("text", "audio", "video", "image", name="mediatype"),
            nullable=False,
        ),
    )
    op.add_column("record", sa.Column("file_url", sa.String(length=500), nullable=True))
    op.add_column(
        "record", sa.Column("file_name", sa.String(length=255), nullable=True)
    )
    op.add_column("record", sa.Column("file_size", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_record_media_type"), "record", ["media_type"], unique=False
    )
    op.drop_column("record", "storage_path")
    op.drop_column("record", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "record",
        sa.Column(
            "type",
            postgresql.ENUM("text", "audio", "video", "image", name="mediatype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "record",
        sa.Column("storage_path", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_record_media_type"), table_name="record")
    op.drop_column("record", "file_size")
    op.drop_column("record", "file_name")
    op.drop_column("record", "file_url")
    op.drop_column("record", "media_type")
    op.drop_column("record", "description")
    op.drop_column("record", "title")
    # ### end Alembic commands ###
