"""centralized_validation_updates

Revision ID: 6c29a2005614
Revises: 82a67997082b
Create Date: 2025-09-02 00:23:37.606183

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c29a2005614"
down_revision: Union[str, None] = "82a67997082b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema with data safety guards."""
    # ### commands auto generated by Alembic - please adjust! ###

    connection = op.get_bind()

    # 1. Check if OTP table has phone_number column and rename to phone if needed
    result = connection.execute(
        sa.text("""
        SELECT column_name FROM information_schema.columns 
        WHERE table_name = 'otp' AND column_name = 'phone_number'
    """)
    ).fetchone()

    if result:
        # Rename phone_number to phone to preserve data
        op.alter_column("otp", "phone_number", new_column_name="phone")
        op.drop_index(op.f("ix_otp_phone_number"), table_name="otp")
        op.create_index(op.f("ix_otp_phone"), "otp", ["phone"], unique=False)

    # 2. Handle record.description NULL values before making NOT NULL
    op.execute(
        "UPDATE record SET description = 'No description provided' WHERE description IS NULL"
    )
    op.alter_column(
        "record", "description", existing_type=sa.VARCHAR(length=1000), nullable=False
    )

    # 3. Clean up release_rights data before enum conversion
    op.execute("""
        UPDATE record 
        SET release_rights = 'NA' 
        WHERE release_rights IS NULL 
           OR release_rights NOT IN ('creator', 'family_or_friend', 'downloaded', 'NA')
    """)

    # 4. Make release_rights nullable with default (avoiding enum conversion to prevent view conflicts)
    # Remove existing default before changes
    op.alter_column("record", "release_rights", server_default=None)

    # Make column nullable and set default without changing type to avoid view conflicts
    op.alter_column(
        "record", "release_rights", nullable=True, server_default=sa.text("'NA'")
    )

    # 5. Clean up language data before enum conversion
    op.execute("""
        UPDATE record 
        SET language = 'NA' 
        WHERE language IS NULL 
           OR language NOT IN ('assamese', 'bengali', 'bodo', 'dogri', 'gujarati', 'hindi', 
                               'kannada', 'kashmiri', 'konkani', 'maithili', 'malayalam', 
                               'marathi', 'meitei', 'nepali', 'odia', 'punjabi', 'sanskrit', 
                               'santali', 'sindhi', 'tamil', 'telugu', 'urdu', 'NA')
    """)

    # 6. Make language nullable with default (avoiding enum conversion to prevent view conflicts)
    # Remove existing default before changes
    op.alter_column("record", "language", server_default=None)

    # Make column nullable and set default without changing type to avoid view conflicts
    op.alter_column("record", "language", nullable=True, server_default=sa.text("'NA'"))

    # 7. Create gender enum type and convert column
    # Check if enum already exists to avoid conflicts
    result = connection.execute(
        sa.text("SELECT 1 FROM pg_type WHERE typname = 'gender'")
    ).fetchone()
    if not result:
        # Create the enum type first
        op.execute("CREATE TYPE gender AS ENUM ('male', 'female', 'other')")

    # 8. Handle user.gender - map invalid values to 'other'
    # First normalize case-insensitive values
    op.execute("""
        UPDATE \"user\" 
        SET gender = CASE 
            WHEN LOWER(gender) = 'male' THEN 'male'
            WHEN LOWER(gender) = 'female' THEN 'female'
            WHEN LOWER(gender) = 'other' THEN 'other'
            ELSE 'other'
        END
        WHERE gender IS NOT NULL
    """)
    # Handle NULL values
    op.execute("""
        UPDATE \"user\" 
        SET gender = 'other' 
        WHERE gender IS NULL
    """)
    # Convert the column using proper casting - this preserves existing data
    op.execute(
        'ALTER TABLE "user" ALTER COLUMN gender TYPE gender USING (gender::text)::gender'
    )
    # Make gender column NOT NULL
    op.alter_column("user", "gender", nullable=False)

    # 9. Handle user NULL values before making NOT NULL
    op.execute(
        "UPDATE \"user\" SET date_of_birth = '1900-01-01' WHERE date_of_birth IS NULL"
    )
    op.execute(
        "UPDATE \"user\" SET place = 'Unknown' WHERE place IS NULL OR place = ''"
    )
    op.execute(
        "UPDATE \"user\" SET hashed_password = 'INVALID_HASH_NEEDS_RESET' WHERE hashed_password IS NULL OR hashed_password = ''"
    )
    op.execute(
        'UPDATE "user" SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL'
    )
    op.execute(
        'UPDATE "user" SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL'
    )

    op.alter_column("user", "date_of_birth", existing_type=sa.DATE(), nullable=False)
    op.alter_column(
        "user", "place", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "user", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "user", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )

    # 10. Drop consent_given_at column if it exists (data will be lost - this is intentional)
    result = connection.execute(
        sa.text("""
        SELECT column_name FROM information_schema.columns 
        WHERE table_name = 'user' AND column_name = 'consent_given_at'
    """)
    ).fetchone()

    if result:
        op.drop_column("user", "consent_given_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    # Restore consent_given_at column
    op.add_column(
        "user",
        sa.Column(
            "consent_given_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )

    # Revert user column constraints
    op.alter_column(
        "user", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "user", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "user", "place", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("user", "date_of_birth", existing_type=sa.DATE(), nullable=True)
    op.alter_column(
        "user",
        "gender",
        existing_type=sa.Enum("male", "female", "other", name="gender"),
        type_=sa.VARCHAR(length=20),
        nullable=True,
    )

    # Revert record columns - remove nullable and default since we didn't create enums
    op.alter_column("record", "language", nullable=True, server_default=None)
    op.alter_column("record", "release_rights", nullable=True, server_default=None)

    # Drop gender enum type only (we didn't create language or releaserights enums)
    try:
        postgresql.ENUM(name="gender").drop(op.get_bind())
    except Exception:
        # Enum type might not exist, ignore the error
        pass

    op.alter_column(
        "record", "description", existing_type=sa.VARCHAR(length=1000), nullable=True
    )

    # Check if we need to rename phone back to phone_number
    result = connection.execute(
        sa.text("""
        SELECT column_name FROM information_schema.columns 
        WHERE table_name = 'otp' AND column_name = 'phone'
    """)
    ).fetchone()

    if result:
        # Rename phone back to phone_number to preserve data
        op.drop_index(op.f("ix_otp_phone"), table_name="otp")
        op.alter_column("otp", "phone", new_column_name="phone_number")
        op.create_index(
            op.f("ix_otp_phone_number"), "otp", ["phone_number"], unique=False
        )
    # ### end Alembic commands ###
