"""add streak tracking to user model

Revision ID: 76ee24a75499
Revises: 2506798be9fa
Create Date: 2025-10-02 11:42:52.490899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "76ee24a75499"
down_revision: Union[str, None] = "2506798be9fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - correct! ###
    op.add_column(
        "user",
        sa.Column(
            "streak_multiplier", sa.Float(), nullable=False, server_default="1.0"
        ),
    )
    op.add_column("user", sa.Column("streak_expires_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - correct! ###
    op.drop_column("user", "streak_expires_at")
    op.drop_column("user", "streak_multiplier")
    # ### end Alembic commands ###
