"""seed_default_roles

Revision ID: 8133bfd89d7c
Revises:
Create Date: 2024-07-31 11:15:30.363686

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision: str = "8133bfd89d7c"
down_revision: Union[str, None] = "1d805b364f52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Define the table structure for the role table for use in the migration
    role_table = table(
        "role",
        column(
            "id", Integer
        ),  # Not strictly needed for insert if autoincrement, but good for completeness
        column("name", String),
        column("description", String),
    )

    op.bulk_insert(
        role_table,
        [
            {"name": "admin", "description": "Administrator role with full access"},
            {"name": "user", "description": "Standard user role with basic access"},
            {
                "name": "reviewer",
                "description": "Reviewer role with record review permissions",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM role WHERE name IN ('admin', 'user', 'reviewer')")
    # ### end Alembic commands ###
