"""add document mediatype support

Revision ID: 82a67997082b
Revises: 06fcfcd36c00
Create Date: 2025-08-29 17:35:14.165074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "82a67997082b"
down_revision: Union[str, None] = "8f79c133a37c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'document' to MediaType enum if it doesn't exist
    connection = op.get_bind()
    result = connection.execute(
        sa.text(
            "SELECT EXISTS(SELECT 1 FROM pg_enum WHERE enumlabel = 'document' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'mediatype'))"
        )
    ).scalar()

    if not result:
        op.execute("ALTER TYPE mediatype ADD VALUE 'document'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL doesn't support removing values from enums directly
    # This would require recreating the enum and updating all references
    pass
    # ### end Alembic commands ###
